Vagrant.configure("2") do |config|
config.vm.define "kube_master_1" do |vm1|
    vm1.vm.box = "bento/centos-stream-9"
    vm1.vm.network "private_network", type: "dhcp", name: "Network Adapter 2"
    vm1.vm.hostname = "master1.devops"
    vm1.vm.provider "vmware_desktop" do |vm1_prov|
      vm1_prov.gui = false
      vm1_prov.vmx["memsize"] = "2500"
      vm1_prov.vmx["numvcpus"] = "2"
    end 
  end
  config.vm.define "kube_worker_1" do |vm2|
    vm2.vm.box = "bento/centos-stream-9"
    vm2.vm.hostname = "worker1.devops"
    vm2.vm.network "private_network", type: "dhcp", name: "Network Adapter 2"
    vm2.vm.provider "vmware_desktop" do |vm2_prov|
      vm2_prov.gui = false
      vm2_prov.vmx["memsize"] = "1200"
      vm2_prov.vmx["numvcpus"] = "1"
    end 
  end  
  
#  config.vm.define "kube_worker_2" do |vm3|
#    vm3.vm.box = "bento/centos-stream-9"
#    vm3.vm.hostname = "worker2.devops"
#    vm3.vm.network "private_network", ip: "192.168.59.22", name: "vboxnet3"
#    vm3.vm.provider "virtualbox" do |vm3_prov|
#      vm3_prov.gui = false
#      vm3_prov.memory = 1024
#      vm3_prov.cpus = 1
#      vm3_prov.name = "kube_worker_node_2"
#    end
#  end

  # config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/add_pub.key"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provision "shell", inline: <<-SHELL
    # yum install -y epel-release
    groupadd kube && useradd kube -g kube -G wheel
    echo 'kube@123' | passwd kube --stdin
    # su kube -c "mkdir -p /home/kube/.ssh && touch /home/kube/.ssh/authorized_keys && chmod 600 /home/kube/.ssh/authorized_keys"
    # cat /home/vagrant/add_pub.key | tee -a /home/vagrant/.ssh/authorized_keys /home/kube/.ssh/authorized_keys
    rm -f /home/vagrant/add_pub.key
    ### INSTALLING AND CONFIGURING KUBERNETES COMPONENTS
    #/bin/sh /vagrant/kube_init.sh
  SHELL
end
