---
apiVersion: v1
kind: Namespace
metadata:
  name: productionone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app-deployment
  namespace: productionone
  labels:
    app: wp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
        - name: wp-container
          image: aayushsapkota9/wordpress_app
          ports:
            - containerPort: 80
          env:
            - name: DB_NAME
              value: "wordpressdb"
            - name: DB_USER
              value: "wordpressuser"
            - name: DB_PASSWORD
              value: "Wordpresspw@123"
            - name: DB_HOST
              value: "db-svc"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db-deployment
  namespace: productionone
  labels:
    app: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:
      containers:
        - name: wp-db-container
          image: mysql:8.0.39
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Devops@123
            - name: MYSQL_USER
              value: wordpressuser
            - name: MYSQL_PASSWORD
              value: Wordpresspw@123
            - name: MYSQL_DATABASE
              value: wordpressdb
          args: ["--default-authentication-plugin=mysql_native_password"]
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: productionone
spec:
  selector:
    app: wp-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-2
  namespace: productionone
spec:
  type: NodePort
  selector:
    app: wp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
